#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

message="$(cat "$1")"
rx="^(WIP: )?(feature|bugfix|chore)\/([a-zA-Z0-9-]+ )+[a-zA-Z0-9-]+$"

if echo "$message" | grep -qE "$rx"; then
  echo "✅ Commit message is valid!"
else
  echo "🚨 Wrong commit message! 😕"
  exit 1
fi